apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vh-server
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        editor: vim
        app: vh-server
    spec:
        containers:
        - image: wucong/vh-server:19-12-29-23-04-56_dev_0.1
          name: vh-server
          volumeMounts:
          - name: vh-dict-volume
            mountPath: /vh/vol/vh-dict
          - name: vh-user-volume
            mountPath: /vh/vol/vh-user
        volumes:
        - name: vh-user-volume
          gcePersistentDisk:
              pdName: vh-user
              fsType: ext4
        - name: vh-dict-volume
          gcePersistentDisk:
              pdName: vh-dict
              fsType: ext4