apiVersion: v1
kind: Pod
metadata:
  name: vh-server
spec:
  containers:
  - name: vh-server
    image: alpine
    command: ["tail"]
    args: ["-f","/dev/null"]
    volumeMounts:
    - name: vh-dict-volume
      mountPath: /vh/vol/dict-data
    - name: vh-user-volume
      mountPath: /vh/vol/user-data
  volumes:
  - name: vh-user-volume
    gcePersistentDisk:
        pdName: vh-user
        fsType: ext4
  - name: vh-dict-volume
    gcePersistentDisk:
        pdName: vh-dict
        fsType: ext4