name: Vh Chrome Extenstion CI

on: push
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: build crx
      run: |
        cd browser-extenstion
        npm ci
        echo "start build crx"
        npm run release-crx
        echo ${{ github.ref }}
        ls
        
      env:
        CI: true
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        CHROME_PEM: ${{ secrets.CHROME_PEM }}

    - name: draft-release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref,'refs/tags/vh-chrome-extenstion-draft-v')
      with:
          files: ./browser-extenstion/vh.crx
          draft: true
      env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref,'refs/tags/vh-chrome-extenstion-v')
      with:
          files: ./browser-extenstion/vh.crx
      env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
