name: Vh Server CI

on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: setup py env
      uses: actions/setup-python@v1
      with:
        python-version: '3.6'
    - name: test
      run: |
        cd server
        ./install.sh
        ./test.sh
        echo ${{ github.ref }}
  push-to-dockerhub:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref,'refs/tags/vh-server')
    steps:
    - uses: actions/checkout@v1
    - name: login docker
      uses: azure/docker-login@v1
      if: startsWith(github.ref,'refs/tags/vh-server-draft-v')
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: push draft image to dockerhub
      if: startsWith(github.ref,'refs/tags/vh-server-draft-v')
      run: |
          cd server
          ./github-ci-push-image.sh ${GITHUB_REF}

    - name: push release image to dockerhub
      if: startsWith(github.ref,'refs/tags/vh-server-v')
      run: |
          cd server
          ./github-ci-push-image.sh ${GITHUB_REF}

  deploy-to-gke:
    needs: push-to-dockerhub

    runs-on: ubuntu-latest
    if: startsWith(github.ref,'refs/tags/vh-server')
    env:
      GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
      GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
      GKE_ZONE: us-central1-a
      GKE_CLUSTER: vh-standard-cluster-1
      IMAGE: gke-test    
    steps:
    - uses: actions/checkout@master
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    - name: deploy to k8s
      run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
        gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE --project $GKE_PROJECT
        ./server/github-ci-deploy-image.sh ${GITHUB_REF}
